### ISSUE TITLE
Cannot open Gists: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by arturl** [vsls-contrib/gistpad#10]
Hi there,

Great extension but doesn't work for me. When trying to open an existing Gist, I get this error

Unable to open '5cee0b498a71a39698c06fb95341xxxx': Unable to read file (TypeError: Cannot read property 'files' of undefined).

**Comment by lostintangent** [comment]
Hmm, I wonder what might be going on here. If you run the “New Gist” command, does that work? I’m just curious if there’s a general issue with the extension for you, or if there’s something up with that Gist?

Is the Gist that you tried to open, a secret Gist? Would you be able to share the ID with me so I could try to repro it?

**Comment by arturl** [comment]
I have the same problem with a public gist: https://gist.github.com/arturl/408c96b717a44a98a3af7546ecc6698c

Here is how the error looks like for me:

![image](https://user-images.githubusercontent.com/1875734/69601713-f31f9d80-0fc9-11ea-82d5-4df42cd2d8e2.png)

**Comment by arturl** [comment]
Also, you asked:
> If you run the “New Gist” command, does that work?

No, that doesn't work either -- it simply doesn't do anything and doesn't show any errors. The gist isn't created in GitHub either.

**Comment by lostintangent** [comment]
This isn’t a GitHub Gist? Could you elaborate further? 😁 Are you using GitHub Enterprise?

**Comment by arturl** [comment]
This is normal gist -- see the link above: https://gist.github.com/arturl/408c96b717a44a98a3af7546ecc6698c

**Comment by brase** [comment]
Same problem here. For me it's not working either.

I don't see any of my gists and when I try to create a new one I got the same error message stated above: 'Cannot read property 'files' of undefined'

**Comment by jimcroft** [comment]
I'm getting similar errors however the gists I can't load all have funky names (ie. contain whitespace, `*`, `:`, `?`, etc. characters in their names). 

eg.

```
Unable to open 'Solr name:* node query': Unable to read file (TypeError: Cannot destructure property `content` of 'undefined' or 'null'.).
```

```
Unable to open 'uwotm8': Unable to read file (TypeError: Cannot destructure property `content` of 'undefined' or 'null'.).
```

The gist names being reported in the errors are wrong, they're actually `Solr *:* node query` and `uwotm?`

refs:

https://gist.github.com/jimcroft/3272471
https://gist.github.com/jimcroft/777f3271712a12465c766ae684e0262b


Creating new gists and other functionality working well here.

**Comment by lostintangent** [comment]
Thanks for all the details! I was able to repro and fix this bug, and I'll ship the fix for it this evening 👍
