### ISSUE TITLE
Feature: Add "Save File as New Gist" command

### ISSUE THREAD

**Issue by JustinGrote** [vsls-contrib/gistpad#109]
Often I'll be writing a file and decide I want to save it as a Gist. Current workflow is not ideal:

1. Ctrl-Shift-P
2. New Gist
3. Fill in the info
4. Browse to the new file
5. Cut and paste from my "old" file to the new one

Preferred workflow:

1. Ctrl-Shift-P
2. Select "Save file as new gist"
3. Pre-populate the file name and only show me the dropdown prompt for what I want the description to be

**Comment by lostintangent** [comment]
If you right-click a file in the Explorer tree, there’s a “Copy File to Gist” command, that lets you copy the selected file to an existing or new Gist. That same command is also available if you right-click the tab for a document window. Would that satisfy your scenario?

**Comment by JustinGrote** [comment]
At least for me, that button didn't work, regardless of if the document was saved or not.
![Capture](https://user-images.githubusercontent.com/15258962/73200928-a735c580-40ec-11ea-8bac-b4775678c8fd.gif)

**Comment by lostintangent** [comment]
That's a bug :) Assuming that this worked, would that satisfy your requirements?

**Comment by JustinGrote** [comment]
Yes. If saved, prepopulate the filename and prompt for description. If
unsaved, prompt for both filename and description

**Comment by lostintangent** [comment]
This fix has been published to the marketplace 👍 Let me know if you have any feedback on the experience.

**Comment by JustinGrote** [comment]
@lostintangent Confirmed that the following story works with this fix:

1. I have an existing saved file and I want to add it to an existing Gist

However the scope of this item included a couple other stories:

2. I have an unsaved untitled file and I want to save it as a new gist and/or an existing gist, and have it reopen the file as the "gist" version (so that future saves go straight to the gist). It will prompt me for both the file name and the new gist name
3. I have a existing saved file I want to create as a new gist. It would prompt me for the gist description and use the file name that already exists.

Trying #2  with "copy file to gist" does nothing.

Also #1 typically is taking 3-5 seconds to open the drop down dialog, and initially I was thinking it wasn't working, any perf improvements that can be done here like just pull up a cached list of gists?

Thanks for your hard work!

**Comment by lostintangent** [comment]
@JustinGrote Hey! I just fixed the performance issue you were seeing and will ship that in a few minutes. Regarding #3, that should already work? If you run `Copy File to Gist` and then scroll to the bottom of the list, you should see a `Create new gist...` item. When selected, it will ask for a description and then use the selected file's name. Was this not working for you?

I can repro #2, so I'm looking into that and will try to get a fix out this morning.
