### ISSUE TITLE
Gists Explorer Should Refresh on First Open

### ISSUE THREAD

**Issue by JustinGrote** [vsls-contrib/gistpad#114]
When opening the gists explorer pane, it doesn't refresh until you perform some sort of other GistPad action. It should refresh on first open.

![image](https://user-images.githubusercontent.com/15258962/72943503-109f8800-3d2b-11ea-9399-e71f5aba43a2.png)

**Comment by yegor-mialyk** [comment]
Steps to reproduce:

- Open VS Code (no files or folders are opened)
- Go to Explorer view
- Expand Gists area

Actual: Gists area is empty
Expected: Gist tree appears

Visual Studio Code:

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by lostintangent** [comment]
Out of curiosity: if you switch to the GistPad tab, instead of the `Explorer` view, do you se the list of Gists?

**Comment by yegor-mialyk** [comment]
yes

**Comment by lostintangent** [comment]
Ah OK, I see the issue. I'm submitting a fix for this right now. Thanks for the helpful repro steps!

**Comment by lostintangent** [comment]
This is now fixed in the latest marketplace update. Thanks for the report!

**Comment by JustinGrote** [comment]
@yegor-mialyk  thanks for the more detailed report. @lostintangent  thanks for the fast fix!
