### ISSUE TITLE
Add support for multi-level directories

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gistpad#125]
Currently, you can organize your gist files into directories, but only a single-level. The notion of gist directories are meant to extend the value of gists, not to replace repos, and so I'm not too sure how valuable it would be to support multi-level directories. That said, I want to track this limitation in order to get feedback from folks, and help inform the prioritization of this work.

**Comment by RandomFractals** [comment]
personally, I think this would be overengineering it for gists. 

I'd rather see native gistpad tagging improvement instead ... https://github.com/vsls-contrib/gistpad/issues/7#issuecomment-590961547

**Comment by lostintangent** [comment]
I’m going to close this now that enough time has passed, and no one has requested it. As was mentioned, I actually don’t think I want to add support for this, particularly now that GistPad supports managing repos in addition to gists 👍
