### ISSUE TITLE
👋 Feedback Wanted: What are you using GistPad for?

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gistpad#127]
Hi! 👋 As part of building out the GistPad experience, we’re very keen to understand what folks are using it for (e.g. maintaining your personal [code snippets](https://twitter.com/marcduiker/status/1206317447483207681?s=21), [collaborating with others](https://twitter.com/uncoded_ls/status/1213975978516586497?s=21), building [interactive playgrounds](https://twitter.com/lostintangent/status/1207718123241033728?s=21), [creating tutorials](https://twitter.com/lostintangent/status/1228780570932498432?s=21) for an online class), to help inform our backlog prioritization, and identify further areas of improvement.

If you’re currently using GistPad (or plan to soon!), it would be extremely helpful if you could share a quick description of your use case, as well as what would be the top thing(s) we could do to improve your workflow. Thanks!

**Comment by caburj** [comment]
I'd like to say that this is an awesome project. I've been looking for ways to organize my notes and I believe this is the solution. 💯 

I have the following recommendations but I don't think they are very important. Anyway, here they go:
1. Playgrounds: Correct me if I'm wrong but so far we can only add script from the cloud. Can we add a feature of adding local scripts instead?
2. Contribution: I would like to study the code and perhaps one day be able to contribute, can you provide some guidance on how to start contributing?

And not to forget, thank you so much for sharing this project to the world. :)

**Comment by lostintangent** [comment]
@caburj That is awesome to hear! Please keep the feedback coming :) Regarding your questions:

1. When you say "local scripts", do you mean a script that is located in the playground gist? Or a script that is on your local file system? Currently, playgrounds allow you to reference other scripts in the gist. So you can create a new script file in the file, right-click a local script and select `Copy File To Gist`, or right-click the gist and select `Upload File(s)` in order to upload a script. Is that what you had in mind?

2. I need to create a `CONTRIBUTING.md` that addresses this question for everyone. I'll try to get to that this weekend, since I definitely want to encourage contributions 👍

**Comment by caburj** [comment]
@lostintangent Your response to my first feedback is very helpful. I got the `local script` work.

I'll take this opportunity to give more feedback. This time about debugging. Wouldn't it be nice to integrate with the playground the debugging capability of VS Code? I'm guessing that it is technically challenging to implement but it would be a very nice feature. :)

Thank you so much for taking time to response. I hope for more successes to this project. :)

**Comment by lostintangent** [comment]
@caburj Hey! We've got an issue tracking the debugging issue here: #123. Maybe we can move the conversation there?

I opened this issue as an experiment to see if it would help increase engagement with users. It didn't really work, so I'm going to close it, and will just rely on folks filing issues on their own. Thanks all!
