### ISSUE TITLE
add gistpad.viewers filenames glob support

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/gistpad#131]
the basic filenames matching worked nicely! I liked it!

see: https://github.com/RandomFractals/geo-data-viewer/issues/54#issuecomment-592229532

we want more! :)

**Comment by RandomFractals** [comment]
@lostintangent any updates on this?

Let me know if you need more info.

**Comment by lostintangent** [comment]
Closing this in favor of the new custom editor and editor association support that’s coming in VS Code: https://code.visualstudio.com/updates/v1_44#_workbencheditorassociations-setting.

**Comment by RandomFractals** [comment]
that interface requires more than just a simple glob fix, but ok!
