### ISSUE TITLE
Executing gists with CodeRunner

### ISSUE THREAD

**Issue by amard33p** [vsls-contrib/gistpad#132]
Not sure if this needs to be addressed in Gistpad or CodeRunner.
Use case:

- Open a (Python) gist script inside GistPad.
- Run the script using CodeRunner.

Since the file does not exist locally, it cannot be executed.

**Comment by lostintangent** [comment]
@amard33p Hey! Thanks for reporting this. This is something that would need to be addressed on the CodeRunner side. Basically, CodeRunner needs to be able to operate on virtual file systems, which GistPad is just one examples (along with others such as FTP, etc.).

Do you want to file an issue on their end, and I can start taking a look at what a PR might look like to update CodeRunner?
