### ISSUE TITLE
Write to the output log when saving/uploading a gist

### ISSUE THREAD

**Issue by johnpapa** [vsls-contrib/gistpad#137]
This s helpful for verifying things are working. Today only SSO messages seem to appear here.

**Comment by RandomFractals** [comment]
I agree. Make it optional tho via a log setting, maybe with different info & debug levels to let devs have a peek at what gistpad does ...

**Comment by lostintangent** [comment]
At this point, GistPad is performing a lot of interactions with the Gist/GitHub API, so I’m not sure how helpful it would be to output this activity to the output window. I’m going to close this for now, and we can reopen it if there is more demand to have this kind of diagnostics experience. Thanks!
