### ISSUE TITLE
CodeTours recorded within Tutorial Playgrounds do not play upon loading Tutorial.

### ISSUE THREAD

**Issue by retrotheft** [vsls-contrib/gistpad#138]
This appears to be due to the way the tour.json file is saved when recording CodeTours, which is in the root folder of the playground. This works for Playgrounds, but not Tutorial Playgrounds. 

Further, this behaviour is different from the Learning MobX Showcase Tutorial which saves a tour.json file within each numbered directory of the Tutorial Playground.

When the recorded CodeTour is altered to contain tour.json files within each step's directory (and the file references appropriately corrected in the tour.json file) the CodeTour plays as expected.

To reproduce:
1. Create a new playground and convert it to a tutorial.
2. Add first step directory and code file, e.g. "1/script.js"
3. Record a CodeTour in "script.js"
4. Reload the Tutorial Playground.

**Comment by lostintangent** [comment]
Hey! Thanks for reporting this. Yeah I implemented the tour “player” to support tutorial steps (which is why the MobX sample works), but the “recorder” currently doesn’t. I wasn’t sure if anyone is actually using tutorials, so I decided to keep things simple to start 😁 That said, I can fix this tomorrow and get a release out.

In the meantime, I’d love to hear if you’re using tutorials and/or CodeTour, and what other feedback you might have 👍

**Comment by retrotheft** [comment]
Legend! Thanks for the quick response. :)

You've actually completely solved a use case I was thinking of about a year ago with these two extensions. Let me explain:

When doing video tutorials, I figured out it was better to create my own notes rather than coding along with the video, and then do the projects from my own notes. It helped with retention and gave me something to refer back to, but was less time efficient due to double handling.

With GistPad/CodeTour though, it's a cake and eat it too deal. I can set up a tutorial for each course, and create a tutorial step for each video in the course (can simply duplicate the step once it's written then move onto the next one). Using CodeTour I'll write explanatory notes, and that way I've simultaneously coded the project and also written explanatory notes to refer back to, and in a really accessible format that doesn't require too much searching for what I'm after.

With either GistPad or CodeTour on their own, this wouldn't be that amazing. You could CodeTour a whole project but the tour would be impossible to manage or find anything. Likewise, the GistPad Tutorial Playgrounds on their own are great but each step can still be a whole video of content, which can be overwhelming and lacks a happy path.

Together though, in all seriousness, this functionality is an app that I would pay for. I expect it will decrease my learning time and increase my ability to execute my own projects afterward.

The fact that you can also export CodePens is serendipitous too since a lot of courses will have their first video using a CodePen to get people involved with the language before explaining how to set up a local dev environment later on.

**Comment by lostintangent** [comment]
@retrotheft This has now been fixed and shipped 👍 Let me know if you run into any problems, and please keep the awesome feedback coming 😄
