### ISSUE TITLE
Unable to install 'vsls-contrib.codetour' extension

### ISSUE THREAD

**Issue by dixonge** [vsls-contrib/gistpad#143]
not compatible with VSCode 1.40.2

![Screen Shot 2020-04-02 at 10 02 07 AM](https://user-images.githubusercontent.com/1578506/78271471-6af65b00-74c9-11ea-95d9-ac56ed2b4318.png)

Did not see any way to install gistpad without this extension, so even though not technically a problem inside gistpad, makes it unusable.

**Comment by lostintangent** [comment]
Thanks for reporting this! Let me push a fix for this right now. Apologies for the inconvenience!

**Comment by lostintangent** [comment]
@dixonge I just published an update to CodeTour that fixes this version issue. Apologies for this, and please let me know if you run into any other issues. Thanks!

**Comment by dixonge** [comment]
@lostintangent wow, that was a fast fix! I use another extension to copy all my existing code snippets from text file to GitHub, but now I removed it and switched back to GistPad. Very nice!
