### ISSUE TITLE
Order of fields upon Gist creation

### ISSUE THREAD

**Issue by IlanVivanco** [vsls-contrib/gistpad#146]
Due to the fact that you can now create a gist with multiple files, wouldn't it be better to first ask for the gist description —it can still be optional— and then for the list of files?

It might be a matter of preference, but I'm always creating them in the wrong order. 🤦 

First step:
![image](https://user-images.githubusercontent.com/9307840/80153306-a26d9a00-8593-11ea-924f-0905d099e478.png)

Second step:
![image](https://user-images.githubusercontent.com/9307840/80153312-a4375d80-8593-11ea-9e2e-13fe0dff6993.png)

**Comment by lostintangent** [comment]
Yeah I agree with this feedback. I'll make this change tomorrow!
