### ISSUE TITLE
Can't log in to github using gistpad

### ISSUE THREAD

**Issue by chrstraub** [vsls-contrib/gistpad#148]
Hi,

I am using Ubuntu 18.04.4 with Visual Studio Code v1.45.0.
I have installed gist 3.0.3 and GistPad 0.0.67.

Gist works fine, I have put in my access token and I can open gists fine. But when I go to the GistPad extension and try logging it just says 'activating extension' at the bottom, but nothing ever happens.
I already tried uninstalling Visual Studio Code and starting from scratch, but that didn't help.

Any idea as to why it won't sign me in? I can't see any error messages.

I am using GistPad + Gist + Visual Studio Code successfully on a Windows machine. And I did the same, first downloaded Gist, signed in an created a profile with an access token. Then started using GistPad - works perfectly.

Thanks,
Christina

**Comment by lostintangent** [comment]
Sorry you ran into this issue! Can you ensure you have “gnome-keyring” and “libsecret” installed? When you sign-in with GistPad, it stores your GitHub token in the OS keychain, and therefore, requires those libs to be installed. On Windows/macOS, the OS already includes all the dependencies needed for GistPad to store/retrieve secure tokens, which is likely why you didn’t have this problem on Windows.

Additionally, the Gist extension stores your token in VS Code’s extension storage (which isn’t secure or encrypted), which is likely why it didn’t have this problem on Linux either.

**Comment by chrstraub** [comment]
Thanks for getting back so quickly!
I saw those comments in the readme and I just double checked again, I have
gnome-keyring v3.28.0.2
libsecret v0.18.6-1
Could it be a version problem perhaps?

Good to know about the Gist extension storage of the token. I didn't know that!

**Comment by lostintangent** [comment]
Hmm, interesting. I’m not aware of a specific version requirement :/

If you try to login with GistPad and then open the VS Code dev tools (via the Help > Toggle Developer Tools menu), do you see any errors in the console? I’ll try to look into this issue later tonight, and see if I can repro it. Apologies again for the problem. I didn’t think we had any issues with auth on Linux.

**Comment by chrstraub** [comment]
I tried that, but nothing pops up in the console?

**Comment by Boss-U** [comment]
I am trying to sign in, created a personal auth token with gist scope. 

Keyring appears to enter a password.
I enter a password/or leave blank both don't matter as, then once I confirm. Nothing happens.

I installed gnome-keyring and libsecret. Running Arch & KDE

I see this in console log:
ERR No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login: Error: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

**Comment by lostintangent** [comment]
Closing this as resolved, since I just shipped support for native VS Code auth. This issue shouldn't repro any longer, but please let me know if it does 👍
