### ISSUE TITLE
Add "Paste Gist File" to command palette 

### ISSUE THREAD

**Issue by yangkennyk** [vsls-contrib/gistpad#151]
I try to avoid using my trackpad as much as I can.

I can't seem to find a way to paste gist content with just the keyboard and it doesn't look like pasting a gist file is documented as an option in the command palette. 

just found this extension by the way. So far it's been pretty amazing. Thanks!

**Comment by lostintangent** [comment]
Hey! You’re right, the ability to paste a gist file is currently limited to the editor’s context menu. I’ll add a command palette option this afternoon and ship that in the next update this evening. Thanks so much for the feedback!

**Comment by lostintangent** [comment]
If you update to `v0.0.68`, then you'll see that the `GistPad: Paste Gist File` command is now exposed in the command palette (as long as you have an editor opened). Let me know if it works well for you!
