### ISSUE TITLE
Maintain behavior of REST Client extension using http files as gists.

### ISSUE THREAD

**Issue by hugufc** [vsls-contrib/gistpad#157]
When I tried to use an .http file as gists I couldn't use the `Send Request` link button as we can see [here](https://github.com/Huachao/vscode-restclient#navigate-to-symbols-in-request-file).

I expected to work as a normal .http file using [REST Client](https://github.com/Huachao/vscode-restclient) extension.

**Comment by lostintangent** [comment]
Thanks for filing this! I’m tracking extensions that need to add support for virtual file systems via #30, so I’m going to close this as a duplicate and we can track progress in that issue. Thanks!
