### ISSUE TITLE
[Bug] open gist command show the search text as first selectable item

### ISSUE THREAD

**Issue by ctf0** [vsls-contrib/gistpad#165]
**Describe the bug**
open gist command show the search text as first selectable item

**To Reproduce**
plz check the gif below

**Expected behavior**
only show the list of found items

**Screenshots**
![demo](https://user-images.githubusercontent.com/7388088/87274654-8f0c0400-c4dc-11ea-9333-78dcfb8fa6b5.gif)

**Desktop (please complete the following information):**
 - VS Code Version [e.g. v1.44.0] 1.48.0-insider
 - GistPad Version [e.g. v0.0.66] 0.1.7

**Comment by lostintangent** [comment]
Hey! This behavior is actually by design, since you can paste a Gist URL or ID into the input box and open it that way. I could probably make this more intuitive by validating the input text, and only adding it to the list if it was a valid URL or Gist ID.

**Comment by ctf0** [comment]
actually we can get around that by waiting for user to press enter, 
so if he wrote something then pressed enter 
- we will treat it as url or gist id, 
- otherwise use it to filter the gist list.

**Comment by lostintangent** [comment]
Hmm, I’m not sure if there’s a way to allow the user to enter input, and not filter the quick pick list? Even if there was, how would to detect whether the user was typing to filter the list or to enter a URL/ID? That’s why I insert the “input item” into the list, so that it doesn’t feel odd to type and see a blank list.

**Comment by ctf0** [comment]
> how would to detect whether the user was typing to filter the list or to enter a URL/ID? 

easy, if the list has items, then we are filtering, otherwise its considered a URL or gist id.
