### ISSUE TITLE
Create new repo from template doesn't show in gistpad commands

### ISSUE THREAD

**Issue by neuroplastic** [vsls-contrib/gistpad#166]
Create new repo from template doesn't show in gistpad commands:

1. Go to 'Repositories' in sidebar
2. Click on '+' to add repo
3. Menu shows 'Create new repo' and 'Create new private repo' - neither 'from template' shows

 - VS Code Version [e.g. v1.47.0]
 - GistPad Version [e.g. v0.1.7]

**Comment by lostintangent** [comment]
This is fixed in the latest GistPad updated 👍

**Comment by neuroplastic** [comment]
Thanks!
