### ISSUE TITLE
Get "TypeError: Cannot read property 'sha' of undefined" when click just created wiki link

### ISSUE THREAD

**Issue by dekhanov** [vsls-contrib/gistpad#167]
**Describe the bug**
Get "TypeError: Cannot read property 'sha' of undefined" when click just created `[[wiki link]]`.

**To Reproduce**
1. I created a repo using [foam-template](https://github.com/foambubble/foam-template)
2. I added the repo into GitPad repositories
"Open Today Page" works just fine
"Add new file" works just fine
If I add a new wiki-link, and press 'enter' a new file creates just fine
3. If I add a new wiki-link, and **without hitting enter** open the link using "option + click", I get an error.

**Expected behavior**
I expect that clicking at new link will create a file.

**Screenshots**
![error](https://user-images.githubusercontent.com/2033947/87503089-7e4ec000-c68d-11ea-835d-64b0faaa7e21.gif)

**Desktop (please complete the following information):**
 - VS Code Version 1.47.1
 - GistPad Version v0.1.7

**Comment by lostintangent** [comment]
Ah good catch! Yeah I currently only create the page if you "accept" the completion item. But I need to also create it when you attempt to ctrl+click it as well. Thanks for reporting this. I'll try to get to it tomorrow 👍

**Comment by lostintangent** [comment]
This is fixed in the latest GistPad updated 👍
