### ISSUE TITLE
[BUG]Error loading other people gist

### ISSUE THREAD

**Issue by roojay520** [vsls-contrib/gistpad#176]
**Describe the bug**
Error loading other people gist after network error
 
**Expected behavior**

**Screenshots**

The gist I own:
<img width="1018" alt="Screenshot_2020-08-04_11-05-38" src="https://user-images.githubusercontent.com/11495164/89249133-03514780-d644-11ea-898a-97a917ac33ec.png">

GistPad show load gist:
<img width="1616" alt="Screenshot_2020-08-04_11-07-59" src="https://user-images.githubusercontent.com/11495164/89249144-0a785580-d644-11ea-8131-68d93dcd9b57.png">

<img width="1616" alt="Screenshot_2020-08-04_11-10-36" src="https://user-images.githubusercontent.com/11495164/89249149-0ea47300-d644-11ea-9fe2-6fb5db14fac6.png">

**Desktop (please complete the following information):**
 - VS Code Version: 1.47.3
 - GistPad Version: 0.1.8

**Additional context**

**Comment by lostintangent** [comment]
I'm not able to repro an issue here, so I'm going to close it. Please re-open this if you're still running into an issue. Thanks!
