### ISSUE TITLE
Add gistpad to Data Science and Visualization extension categories

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/gistpad#178]
as a vscode marketplace SEO enhancement since this extension ships with some data viz playground gists for data scientists to try.

VSCode v1.48.0 and vscode marketplace now allow to find extensions by category, with new Data Science and Visualization categories added recently. See: https://code.visualstudio.com/updates/v1_48#_extensions-overflow-menu-cleanup

In order to enable this SEO enhancement, we just need to update categories in `package.json`. I would also suggest we add Snippets since gists can be viewed as short code snippets in loose terms.

Proposed changes to `package.json`:

```
"categories": [
    "Data Science",
    "Other",
    "Snippets",
    "Visualization"
  ]
```

What those category filters look like in extensions view panel:

![vega-viewer-data-science](https://user-images.githubusercontent.com/656833/90313781-c8b59d80-ded4-11ea-9ed2-f6ac57cac543.png)
``

**Comment by lostintangent** [comment]
Thanks for contributing this!
