### ISSUE TITLE
Add support for github enterprise

### ISSUE THREAD

**Issue by KnisterPeter** [vsls-contrib/gistpad#18]
It would be great to read gists from github enterprise as well.

In the used libs (gist and github-base) it should be doable by setting `apiurl` key in the line https://github.com/vsls-contrib/gist-fs/blob/master/src/api.ts#L36

Not sure if there are options right now, or if it would be good to support github and github enterprise next to each other.

**Comment by lostintangent** [comment]
Thanks for the feedback! I’ll look into this today 👍

**Comment by guyk-yahoo** [comment]
I'd love that too

**Comment by lostintangent** [comment]
Just released `v0.0.3`, which introduces a `gistpad.apiUrl` setting. You should be able to set that to your GitHub Enterprise instance's API URL (e.g. `https://[YOUR_HOST]/api/v3`). I don't have access to GitHub Enterprise, so I can't actually test it :/ So it would be awesome if someone could help me verify this. In the meantime, I'll close this issue, but please re-open it if the setting doesn't work. Thanks!
