### ISSUE TITLE
Proposed API disabled?

### ISSUE THREAD

**Issue by fdncred** [vsls-contrib/gistpad#183]
**Describe the bug**
Today I started getting this notification in vscode-insiders when I click on the gitspad icon. Is there something else I need to do to get this working again? I've been using it a while now and am addicted to it. :)
```
[vsls-contrib.gistfs]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vsls-contrib.gistfs
```

**Desktop (please complete the following information):**
 - VS Code Version [e.g. v1.44.0] 1.50.0-insider
 - GistPad Version [e.g. v0.0.66] 0.1.8

**Comment by lostintangent** [comment]
I haven't been able to repro this, so I'm going to close it. That said, please re-open it if you're continuing to encounter this issue. Thanks!
