### ISSUE TITLE
Ability to change scratch note naming format

### ISSUE THREAD

**Issue by celynwalters** [vsls-contrib/gistpad#190]
**Is your feature request related to a problem? Please describe.**
Scratch notes are named with the current date in a format such as `November 19, 2019.md`.
I like to write in here, then move to a 'real' gist with the same name (and an appropriate tag) when I'm sure I won't scrap it.
Personally, I'd prefer not to have a comma in the filename, and be something like YYYY-MM-DD for sorting (if I'd need to).

**Describe the solution you'd like**
I'd like to be able to specify the naming convention.
Sorry I can't suggest the optional scheme, maybe someone can weigh in.

**Describe alternatives you've considered**
Renaming files manually. It might be easier if you could use the `F2` shortcut in the explorer sidebar, but you would still have to type.

**Comment by lostintangent** [comment]
Hey! There's actually a setting you can use to overwrite the filename. It's called "gistPad.scratchNotes.fileFormat", and it takes a [Moment.Js format string](https://momentjs.com). To use the format you mentioned, you could set this to "YYYY-MM-DD". Let me know if that works for you!

**Comment by celynwalters** [comment]
Ah! Perfect, thanks a lot!

Maybe I missed it because of the setting name. "File Format" to me suggests the file content rather than its name, though the setting description is fine.

I'm happy to close this though since it solves my issue.
