### ISSUE TITLE
How long do you expect the token be valid?

### ISSUE THREAD

**Issue by lambdai** [vsls-contrib/gistpad#192]
I am running vscode 1.51.1 on several PCs.

What I found is that the token are somehow lost after vscode restart/upgrade/OS restart. 

I haven't figured out the stable way to reproduce.

Is anyone bother by the similar?

Thanks!

``` vscode
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.7.17-1rodete4-amd64
```

I am also using vscode's setting sync. Not sure if it is related.

**Comment by lostintangent** [comment]
Hey! It shouldn't ever expire. That said, it's possible that there's an issue with certain Linux distros. I need to replace the current token solution, by integrating GistPad natively into the new VS Code authentication provider. That should help improve the robustness of the auth support for GistPad 👍

I'll use this issue to track that change, and I'll plan to get to it next week.

**Comment by lostintangent** [comment]
Closing this as resolved, since I just shipped support for native VS Code auth. This issue shouldn't repro any longer 👍
