### ISSUE TITLE
gistpad.playgrounds.autoSave should default to false

### ISSUE THREAD

**Issue by mithunshanbhag** [vsls-contrib/gistpad#195]
**Is your feature request related to a problem? Please describe.**
Out of the box, the setting `gistpad.playgrounds.autoSave` defaults to `true`. Many a times, this leads to accidental edits being persisted to the github gists. 

I now have to visit `gist.github.com` to see the gist's revision history and figure out how to undo these accidental changes.

Most of the times, I simply wish to open my gists for reading/viewing only.

**Describe the solution you'd like**
The setting `gistpad.playgrounds.autoSave` should default to `true`. Let the users choose to explicitly persist changes (if any).

**Describe alternatives you've considered**
Another alternative is to open gists in a read-only mode by default.

**Comment by lostintangent** [comment]
Thanks for reaching out! Out of curiosity: are you seeing the auto-save functionality impacting non-playground gists? If so, that would be totally unexpected 😁

Either way, I agree with your proposal here, and I'll update the setting in the next release 👍

**Comment by mithunshanbhag** [comment]
Thank you. 

PS: I'm not entirely sure what a "playground" vs "non-playground" gist means. I was referring to the accidental edits possible to gists under `Your Gists` 

![image](https://user-images.githubusercontent.com/2327905/100487569-5d17d900-312f-11eb-889f-1abefaad3b55.png)

**Comment by lostintangent** [comment]
This change has been shipped 👍

**Comment by mithunshanbhag** [comment]
Thanks, verified!

![image](https://user-images.githubusercontent.com/2327905/100533055-21136f80-3226-11eb-883c-4ec2f0c51593.png)
