### ISSUE TITLE
Allow adding the editor selection to a Gist

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gistpad#27]

**Comment by IlanVivanco** [comment]
This would be a great feature!

**Comment by lostintangent** [comment]
@IlanVivanco Just as an FYI, I added support for being able to right click a file in the Explorer tree, or an open document window, and selecting “Add to Gist”. That way, you can migrating local files to gists. This item is then tracking the ability to migrate a snippet of code from a local file, instead of the entire file.

**Comment by IlanVivanco** [comment]
Excellent!

**Comment by lostintangent** [comment]
Just published an update to the marketplace that includes a new `Add Selection to Gist` context menu to the editor.

**Comment by IlanVivanco** [comment]
I can only add documents or selections to existent Gists. Typing the new gist name does not do anything.

**Comment by IlanVivanco** [comment]
Also, names/descriptions in that window are dups
![image](https://user-images.githubusercontent.com/9307840/69882042-a845a480-12ad-11ea-97c4-50cf718158af.png)

**Comment by lostintangent** [comment]
Yeah that’s the current behavior: you can only add files/selections to existing gists. I’ll reopen this issue to track the ability to add a document/selection to a new Gist.

**Comment by lostintangent** [comment]
These issues have been fixed and published to the marketplace!

**Comment by IlanVivanco** [comment]
Great!
