### ISSUE TITLE
Sort Gists by last updated

### ISSUE THREAD

**Issue by escamoteur** [vsls-contrib/gistpad#33]
Hi, It would be awesome if we could toggle the sorting between alphabetical and Last Updated to make it easier to find the most recent Gists

Awesome AddIn!

**Comment by lostintangent** [comment]
I’ll add this later today 👍

**Comment by lostintangent** [comment]
Just published `v0.0.3`, which changes the default sort order of gists to their last updated time. Let me know if this works for you!
