### ISSUE TITLE
Bad Credentials in Git Enterprise integration - can't login

### ISSUE THREAD

**Issue by guyk-yahoo** [vsls-contrib/gistpad#34]
Hey.
As suggested, I updated the settings for GitAPI:
```"gistpad.apiUrl": "https://git.myOrg.com/api/v3"```

I got the relevant AccessToken and set it in VS Code - when I do that. I get "Bad Credentials" error.
![image](https://user-images.githubusercontent.com/30230848/70387008-7ff23000-19a8-11ea-82ab-c7f9f7505c9f.png)

But when I use the same API URL and the same token - I do get the results right:

![Screen Shot 2019-12-08 at 10 43 15](https://user-images.githubusercontent.com/30230848/70386998-6650e880-19a8-11ea-8abc-b3c5e00ef020.png)

Is there a way to debug what's wrong?

**Comment by lostintangent** [comment]
Thanks for reporting this! This error indicates that the token isn’t valid for accessing the Gists API. Couple of follow up questions:

1. Could you try appending “/gists” to the URL you’re trying to hit in Postman (or whichever HTTP you’re using) and see if that works? 

2. Could you verify that the token you generated included the gist scope?

Thanks!

**Comment by guyk-yahoo** [comment]
> Thanks for reporting this! This error indicates that the token isn’t valid for accessing the Gists API. Couple of follow up questions:
> 
> 1. Could you try appending “/gists” to the URL you’re trying to hit in Postman (or whichever HTTP you’re using) and see if that works?
> 2. Could you verify that the token you generated included the gist scope?
> 
> Thanks!

1. Yeah `https://git.myorg.com/api/v3/gists` also works and returns the gists
2. Double checked that -- indeed it includes gists.

Anywhere to look at debug logs?

**Comment by guyk-yahoo** [comment]
Damn...
It started working all of a sudden.

**Comment by guyk-yahoo** [comment]
Maybe I'll add the following.
The `Open Gists` command (CMD+P) actually works:

![image](https://user-images.githubusercontent.com/30230848/70742483-79c6c100-1cd2-11ea-9267-109f66ddef4a.png)

But the side menus don't

**Comment by lostintangent** [comment]
@guyk-yahoo Interesting! The command palette and tree views work off the same data store, so it would seem like the authentication is working, but maybe you have an issue with the tree? Did you try both the `Gists` view on the `Explorer` tab, as well as the entirely separate `GistPad` tab? Do neither work for you?

**Comment by GuyKh** [comment]
> @guyk-yahoo Interesting! The command palette and tree views work off the same data store, so it would seem like the authentication is working, but maybe you have an issue with the tree? Did you try both the `Gists` view on the `Explorer` tab, as well as the entirely separate `GistPad` tab? Do neither work for you?

Yep. 
Both doesn't work

**Comment by guyk-yahoo** [comment]
@lostintangent 
I think I have found the problem when I tried to debug the issue manually.

In the compiles `utils.js` - I'm getting this (HardCoded):
![image](https://user-images.githubusercontent.com/30230848/70752328-36c31880-1ce7-11ea-8bd0-8ee1967864de.png)

When I switch `https://api.github.com` in that compiled file - everything works well.

I'm not sure about how settings are recompiling the sourcecode, but that's a good lead

**Comment by GuyKh** [comment]
@lostintangent ummmm I think I solved it.
Checkout the PR ^^

**Comment by lostintangent** [comment]
Yep you solved it :D Just merged your PR and I'll ship that in a few minutes  👍

**Comment by lostintangent** [comment]
Just shipped the update with this fix. Thanks so much for your help here!

**Comment by guyk-yahoo** [comment]
@lostintangent - Hey.
In the **Explorer** everything seems to be right.
In the dedicated **Gist** tab - it's still empty :(

![image](https://user-images.githubusercontent.com/30230848/70762595-f32bd700-1d05-11ea-82a3-edff594a9f33.png)

**Comment by lostintangent** [comment]
Are you using VS Code Insiders or Stable?

**Comment by GuyKh** [comment]
Stable

**Comment by lostintangent** [comment]
Do me a favor and open the GistPad and then reload VS Code (running the “Reload Window” command). After doing that, does the tab get populated with data?

I think there might be a bug in VS Code, where if a tree view is contributed to two different tabs, then only the first one that’s loaded is rendered properly.

**Comment by guyk-yahoo** [comment]
@lostintangent 
Yeah - I did exactly this - only one of the two will work.
Known bug?
