### ISSUE TITLE
Show nothing in VIEW in mac.

### ISSUE THREAD

**Issue by hujianxin** [vsls-contrib/gistpad#37]
Show nothing in View, but have content in Explorer.

![image](https://user-images.githubusercontent.com/9526904/70436970-75798880-1ac5-11ea-971a-fdb19f8e3c72.png)

![image](https://user-images.githubusercontent.com/9526904/70437001-8a561c00-1ac5-11ea-93d4-9649147f1e4d.png)

OS: 
![image](https://user-images.githubusercontent.com/9526904/70437027-9b9f2880-1ac5-11ea-9844-652b52c0b241.png)

**Comment by lostintangent** [comment]
@hujianxin Hmm, that's unusual. Are you using VS Code Insiders by any chance? I'm just wondering if there's a bug in a version of VS Code. The tree view is exactly the same between the `Explorer` tab and the custom `GistPad` tab, so I'm not sure how one of them wouldn't work. Let me look into this.

**Comment by hujianxin** [comment]
aha, code-insiders solves this problem

**Comment by hujianxin** [comment]
maybe next stable version will fix this automatically

**Comment by lostintangent** [comment]
OK cool, I'll close this as resolved then, and we can re-open it if this isn't fixed by VS Code.
