### ISSUE TITLE
Allow for local access with "reveal with explorer" and "copy file path"

### ISSUE THREAD

**Issue by JustinGrote** [vsls-contrib/gistpad#38]
Gists should be available on the local file system, for instance if you want to dot source them into a demo or something. Currently you have to copy the file to a temporary location before you can use it. The module extension temp folder would be a good location, and tie this URI into the "Copy Path" and "Open in Explorer" functions.

**Comment by lostintangent** [comment]
After taking a quick look at your Gists, I wonder if it would be simpler to add a `Run file in terminal` command to the tree, that would transparently download the file to a temp location and then run it in the VS Code integrated terminal. That way you don't need to deal with local temp files simply to evaluate scripts in a gist. Thoughts?

**Comment by JustinGrote** [comment]
@lostintangent Well things get tricky there because if you want to do debugging, etc. you need to set breakpoints and ideally within lines on a file, so it has to be in a reasonably stable location and be "open"

I envision a user setting that, rather than opening the file in the "ephemeral" state it gets opened today, when doing an open action, it first gets copied to a temp filesystem and then opened from there in vscode, and when saved and closed, re-uploaded.

So, same transparent download as you mentioned, but then opened in vscode. Saving back changes I guess would be a secondary priority, but it beats my current workflow if I need to debug of:
1. Open file
2. Copy contents
3. Paste to a temp file
4. Run my Powershell Debugging ,etc.
5. Paste "fixed" code back to the gist tab and save it

**Comment by JustinGrote** [comment]
So after thinking on this, since the gists are just git repositories, what would be ideal is add a command gistpad.checkoutGist that would trigger the vscode "git clone" activity with the URI of the gist and download the Gist as a git repository to that path. Then it can be worked with like a normal repository if you have any advanced needs, and should be fairly simple to implement.

What do you think @lostintangent?

**Comment by lostintangent** [comment]
@JustinGrote That's a great idea! I can easily add that in the next day or two :)

**Comment by lostintangent** [comment]
Just shipped an update to the extension that adds a new `Clone Repository` context menu to the gist. Let me know what you think!

**Comment by JustinGrote** [comment]
Works as expected, thanks!
