### ISSUE TITLE
Support drag and drop for files within the Gist view

### ISSUE THREAD

**Issue by Mumcio** [vsls-contrib/gistpad#40]
Hi, what do you think about adding similar feature as gist manager has? 
https://marketplace.visualstudio.com/items?itemName=CONWID.GistManager

**Comment by lostintangent** [comment]
Great suggestion! Unfortunately, I don’t believe that VS Code currently supports this sort of scenario, so we’d likely need some new APIs. 

@egamma Can a node in a custom tree view be dragged and dropped on an editor? If not, have you heard of any other requests for this support?

**Comment by lostintangent** [comment]
In the meantime, you can right-click on an open editor and select “Paste Gist File”. It’s not a complete solution to your request, but it might be useful?

**Comment by Mumcio** [comment]
I found workaround to speed up copy/pasting old gist to have them better organized.

Scenario:
1. Open old gist do not close it
2. Right click on new gist node where you want to move the old one
3. Choose "Add Active File" from context menu

 Regarding drag & drop I will take a look how or even if it can be achieved.

**Comment by Mumcio** [comment]
Sure it is a right way. I am curious how this can be achieved I will do the research.

**Comment by lostintangent** [comment]
@Mumcio Sounds good. Thanks!

**Comment by lostintangent** [comment]
See #41 for more details

**Comment by egamma** [comment]
@lostintangent regarding

>@egamma Can a node in a custom tree view be dragged and dropped on an editor? If not, have you heard of any other requests for this support?

Custom tree views currently do not support drag&drop. This is the feature request https://github.com/microsoft/vscode/issues/32592.

**Comment by lostintangent** [comment]
@Mumcio FYI, I added a “Copy File to Gist” menu to files in the gists tree, which allows you to copy files between gists without needing to open them first. This command was already available on the file Explorer, so you can now move between gists and from the local file system. Additionally, there’s a new “Duplicate Gist” command, which allows you to create an entirely new Gist from an existing one. 

I’m planning to add multi-select support to the tree, which would allow you to run the “Copy File to Gist” command on multiple files at a time. Once that’s in, I’m wondering if that satisfies most of the use cases you had in mind? Drag and drop could then be a nice UX improvement down the road, once (if?) VS Code adds support for it.

**Comment by Mumcio** [comment]
Nice @lostintangent I like "Copy File to Gist" it speed up ordering gist well. I am using gistPad each day, I am so impressed about your support. I thought about multiselect, but you were much quicker ;)

**Comment by lostintangent** [comment]
`Copy File to Gist` now supports multi-select, so I'm going to close this issue as resolved. It might be a while before we get drag/drop support, and so I think this might be the best solution for now. Let me know if you have any other feedback. Thanks!
