### ISSUE TITLE
Allow easily moving files amongst Gists

### ISSUE THREAD

**Issue by Mumcio** [vsls-contrib/gistpad#41]
Hi, if user've got a lot of gist and he wants to organize them, he needs to repeat actions like copy content from old gists, then delete them. 

Suggestion:
- drag & drop can resolve this and simplify gist management, organization

**Comment by lostintangent** [comment]
Hey! Thanks for reaching out. Could you clarify what behavior you’re interested in with this issue? Are you thinking that you’d like to drag and drop files within the Gist tree view? So that you can move files from one Gist to another?

If so, I don’t believe that’s currently possible in VS Code, so I’d need to discuss a new API with the team.

**Comment by Mumcio** [comment]
Hi, to clarify 
#40 - is pointing to drag & drop gist content to open editor document
#41 - is pointing to drag & drop gist in tree view between gist nodes 

Regarding #41 I found workaround to speed up copy/pasting old gist to have them better organized.

Use case scenario:
1. Open old gist do not close it
2. Right click on new gist node where you want to move the old one
3. Choose "Add Active File" from context menu

**Comment by lostintangent** [comment]
Ah OK, that makes sense. In addition to the workaround you mentioned, you could also simply open the old Gist file, right-click the editor and select “Add Document to Gist”. 

That said, maybe there are other improvements we could make to simplify the process of moving files between Gists. In your workflow, are you simply moving individual files between Gists, or are you looking to migrate all files from a Gist and then delete the old Gist? 

As I mentioned in #40, I don’t believe there are sufficient VS Code APIs to enable this scenario. But I’ll look into it. Thanks again for the excellent suggestions 👍

**Comment by Mumcio** [comment]
I found thread on vscode about adding drag&drop to tree view API. They do not have plan to implement this feature. I think this will block #40 & #41. It's a pity.

https://github.com/Microsoft/vscode/issues/32592

**Comment by lostintangent** [comment]
@Mumcio Thanks for digging this up! Yeah, @egamma may have an update here, but in the meantime, we'll have to try to find alternative solutions. Do you think the workarounds we've discussed are sufficient for now? Or are there other improvements we can make, in lieu of having drag and drop support?

**Comment by lostintangent** [comment]
Since neither #40 or #41 will be possible until we have a new set of APIs from VS Code, I wonder if we shouldn’t consolidate them into one issue that tracks drag and drop support in general?

**Comment by Mumcio** [comment]
Right, will be much better to merge them.

**Comment by lostintangent** [comment]
K cool, I’ll close this one and then update the title of #40 to reflect the broader scope. Thanks!
