### ISSUE TITLE
Comment box cover over code

### ISSUE THREAD

**Issue by Mumcio** [vsls-contrib/gistpad#42]
It would be better to collapse comment box when user will open gist file. 
If user would like to comment file then he will show comment box via right button next to line number
![image](https://user-images.githubusercontent.com/9086133/70849898-e2ee3600-1e84-11ea-8f03-e83d6fb78a0f.png)

https://github.com/vsls-contrib/gistpad/blob/2e2b540c8f530446628d4f5ac758adc2f89b0ff2/src/comments/index.ts#L60

In API doc there is possibility to collapse

https://code.visualstudio.com/api/references/vscode-api#CommentThread

**Comment by lostintangent** [comment]
Yep agreed. I’ll tweak the behavior here 👍

**Comment by lostintangent** [comment]
This behavior has now been fixed, and I deployed an update to the marketplace. I added a new `Gistpad: Always Show Comments` setting, that allows the user to control whether to show comments by default when opening a Gist file. It defaults to `false`. Let me know what you think!
