### ISSUE TITLE
GISTS tree on Explorer view disappears when switching to GistPad view (Activity bar) and back

### ISSUE THREAD

**Issue by yegor-mialyk** [vsls-contrib/gistpad#44]
Steps to reproduce:
1) Open VS Code (no  files or folders are opened)
2) Go to Explorer view
3) Expand Gists area (a Gist tree appears)
4) Switch to GistPad in Activity bar (a Gist tree re-appears)
5) Switch back to Explorer view / Gists area

Actual: Gists area is empty (no Gist tree)
Expected: Gist tree re-appears

VS Code information:
Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by lostintangent** [comment]
@egamma Any thoughts here? I’m defining a single view and simply contributing it to a custom activity bar as well as the explorer bar. That seems like it should work well, so I’m wondering if this rendering issue is a VS Code bug?

**Comment by egamma** [comment]
@lostintangent I can reproduce as well. What is special in your scenario is that you have the same view contributed once to the Explorer and once to the GistPad View. 

Given that it can be easily reproduced we should investigate what is going on. Adding @alexr00.

**Comment by lostintangent** [comment]
@egamma Thank you! I registered the view twice and that resolved the issue.

The fix for this has now been deployed to the marketplace. Thanks for reporting this issue!
