### ISSUE TITLE
Unable to use ESC or ENTER when searching in active file

### ISSUE THREAD

**Issue by roberehl** [vsls-contrib/gistpad#45]
### Steps to reproduce:
1. Open a gist file using gistpad.
2. Show search bar using COMMAND+F.
3. Press ESC button.
### Result:
- Nothing happens.
- Search bar is not dismissed.
### Expected:
- Search bar should be dismissed.

### Steps to reproduce:
1. Open a gist file using gistpad.
2. Show search bar using COMMAND+F.
4. Type something to search.
3. Press ENTER button.
### Result:
- Nothing happens.
### Expected:
- Find next match action should be triggered.

## gistpad version: 
0.0.21
## VSCode info:
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by lostintangent** [comment]
Thanks for reporting this! Let me take a look and see what might be going on.

**Comment by roberehl** [comment]
You're welcome. By the way, love using this extension. Thanks for the hard work!

**Comment by lostintangent** [comment]
This should now be resolved. Please reopen if you’re still running into a problem. Thanks
