### ISSUE TITLE
Opening markdown file open preview window instead of editor

### ISSUE THREAD

**Issue by karl-lunarg** [vsls-contrib/gistpad#49]
This problem does not occur with 0.0.16 and prior.  It happens with 0.0.17 and later.

Reproduce by trying to open a markdown file in a gist from the explorer window.  A preview pane appears instead of an editor.

I suspect this may be caused by this new code in commit f9d9c08c2f9e13b5c71bd873e36da1371390f507:

```typescript
export async function openGistFile(uri: Uri) {
  const extension = path
    .extname(uri.toString())
    .toLocaleLowerCase()
    .substr(1);
  let commandName;
  switch (extension) {
    case "md":
      commandName = "markdown.showPreview";
      break;
    //case "ipynb":
    //  commandName = "python.datascience.opennotebook";
    //  break;
    default:
      commandName = "vscode.open";
  }
```

It looks like it is intentionally doing a preview for a markdown file.  This makes it impossible to locally edit markdown files in a gist.  I admit to not reading all the code to fully understand this, but it looks suspicious.

I've tried disabling all markdown extensions with no improvement.  And I'm not certain if I am doing anything wrong, so please let me know if that's the case.

**Comment by lostintangent** [comment]
Yeah this was an intentional change, but I’ve had feedback from others as well, so I’ll change it this afternoon. Sorry for the confusion!

**Comment by lostintangent** [comment]
This has now been fixed and released to the marketplace. Thanks for the feedback!

**Comment by karl-lunarg** [comment]
Confirmed fixed/updated.  Thanks!

I didn't know about that "Show Source" icon in the File toolbar.  Good to know.

This behavior makes sense and seems to better support the blog workflow.  And I'm sort of used to conjuring up the preview manually when/if I need it.

There still may be some value in having a preview display when opening a markdown file.  For example, it might be possible to open the file and the preview at the same time, controlled by a user option.  Or, add a "Preview" option in the right-click context menu in the Gist Explorer.

Thanks for this extension!  It is pretty powerful.  I don't naturally use a lot of gists in my workflow, but this extension makes it easy to at least manage gists and gives me an excuse to use them more often!
