### ISSUE TITLE
Always ask for github token

### ISSUE THREAD

**Issue by ricardson** [vsls-contrib/gistpad#52]
Issue Type: <b>Bug</b>

I'm trying to use gistpad but I cannot create my gist and always I have to insert the github token, I create a new one and still the same.

Extension version: 0.0.25
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.19.86

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3821)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.53GB (12.93GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lostintangent** [comment]
Hmm, I wonder if it’s a keyring issue. Do you have gnome-keyring and libsecret installed? Those dependencies are required in order for GistPad to securely store/remember your token.

**Comment by ctf0** [comment]
@lostintangent on mac it asks for login from time to time
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

if u need more info plz tell me.

**Comment by ctf0** [comment]
i think i've found the issue, the ext saves the token in the global storage which depend on ur OS it might/not work as expected all the times, i wonder why not save it into a settings file ?, at least this way the user can sync it between devices.

**Comment by escamoteur** [comment]
I had the same issue today on Windows. As I haven't stored the token elsewhere that is annoying.

**Comment by lostintangent** [comment]
I just shipped an extension update that includes a bunch of logging for auth (without exposing tokens or anything). If you encounter this issue again, could you open up the GistPad output window and then share the contents? That should help me narrow down the issue. Sorry for the inconvenience here!

**Comment by ahmednrana** [comment]
Tried generating tokens many times but still cannot log in. It always asks for a token

**Comment by lostintangent** [comment]
@ahmednrana What OS are you on? Also, could you open the GistPad output window and share the contents?

**Comment by ahmednrana** [comment]
I am using macOS 10.14.6 (18G95) but today I just tried and it logged in fine.

**Comment by ctf0** [comment]
@lostintangent here is the output 
```
[info][Mon, 06 Jan 2020 09:05:44 GMT] GistPad output channel initialized.
[info][Mon, 06 Jan 2020 09:05:44 GMT] Not signed in, attempting git SSO...
```

**Comment by itlackey** [comment]
Not sure if I should create a new issue for this or not but may be related. I am on linux (KDE Neon) and when I click Sign in to view your Gists... it asks for my token. I provide the token and it returns this error in the output windows:
`Token test failed: getaddrinfo EAI_AGAIN undefined`

There is also a notification displayed: The specified token isn't valid or doesn't inlcude the gist scope. Please check it and try again.

I have created three different tokens. All with Gist scope and none of them work. If you need more info or prefer I open a new issue please let me know.

Thanks!

**Comment by lostintangent** [comment]
@itlackey Are you using a proxy and/or GitHub Enterprise? It seems like the token was valid, but GistPad had a connectivity issue when authenticating.

**Comment by lostintangent** [comment]
This issue should be resolved now, and we can track any proxy issues via separate issues. Thanks!

**Comment by douglance** [comment]
I am still having to log in to Gistpad every time I open VSCode. Is there a way for me to get you logs or more information?

**Comment by atatimelikethis** [comment]
Adding to the list, actually I just gave up and uninstalled GistPad (shame I love it), I'm wondering if this is a linux keyring issue, mostly because I run a chromebook on debian and have had this with other extensions (tho they are fixable)
