### ISSUE TITLE
Add support for other playground languages

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gistpad#57]
Currently, you can create playgrounds using the following languages: HTML/Pug, CSS/SCSS/Less, and JavaScript/TypeScript. In all cases, the code is compiled as needed, as you type, without the user needing to do anything. This makes it really easy to visually iterate on code, using whichever languages you’re most productive with.

In order to continue supporting other developer preferences, I’d love to hear feedback about which additional languages would be useful to have. For example: [Stylus](https://codepen.io/jh3y/pen/rNawvYm), [Haml](https://codepen.io/vcurd/pen/VwYbEom), Elm, PureScript, Vue single file components, Svelte, etc. I’ll also continue to survey the CodePen ecosystem to see what folks are using in practice, to make sure that GistPad playgrounds provide strong interop with the community.

**Comment by RandomFractals** [comment]
Could you provide some documentation on how to create new playground PR?

& make it extensible and pluggable?

then devs working on different ecosystems can create configs for playgrounds of their tech, tooling and frameworks interests ...

**Comment by lostintangent** [comment]
@RandomFractals I haven’t created any docs yet because I’m working on the extensibility support for enabling new languages right now. I don’t think I want to ship too many more languages in GistPad itself, as opposed to enabling language extensions to include Gist playground support in them.

**Comment by RandomFractals** [comment]
that's what I meant. I think you can let other extensions hook up into GistPad playgrounds without embedding them if you can provide simple commands.executeCommand(<openView>, gistFileUri) interface, where open view is 3rd party ext. command, and let devs config it in GistPad via settings as for custom file viewers as I have suggested on twitter last month.

Is that still the plan || something along those lines? Thanks!

**Comment by lostintangent** [comment]
As the title implies, this issue is tracking an enhancement to enable [playgrounds](https://github.com/vsls-contrib/gistpad/blob/master/README.md#interactive-playgrounds) to support custom languages. Customer viewers is a different scenario, since adding support for Stylus (for example) doesn’t need a new viewer, it just needs to handle compiling Stylus to CSS.

I’ll open a different issue for the custom viewers scenario.

**Comment by lostintangent** [comment]
Closing this as resolved now that GistPad exposes extensibility for adding new languages. It’s currently limited to markup languages, but we can add support for stylesheet/script languages if the community needs it 👍
