### ISSUE TITLE
Allow pasting images into HTML files

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gistpad#58]
We currently contribute the “Paste Screenshot” command, to make it easy to upload/insert images from your clipboard and into markdown files. However, to improve the playground experience, we should also allow this command to be run in HTML files, so that local images can be easily used in playgrounds, without the user needing to manually upload it to the Gist or an image hosting service.

**Comment by legomushroom** [comment]
I can look into this.

**Comment by lostintangent** [comment]
I already shipped this actually :)
