### ISSUE TITLE
Persist the expanded/collapsed state for root-level tree nodes

### ISSUE THREAD

**Issue by ctf0** [vsls-contrib/gistpad#65]
for example 
- sorting
- collapsed groups

**Comment by lostintangent** [comment]
Hey! Sort order should already be persisted, and remembered across different VS Code sessions. Are you not seeing that behavior?

Regarding collapsed groups: right now, we only auto expand the “Your Gists” and “Starred Gists” nodes. Out of curiosity: is there a better default you'd prefer? That may be another enhancement, besides persistent collapsed node state.

**Comment by ctf0** [comment]
u r right regarding the sorting, my bad, for a moment it wasnt working.

for the collapse, i think u can save it same as u do with the sorting "workspace.storage i presume"

i honestly wanted to ask for an option to hide the starred gists all together, but i thought the collapse persistence would be enough.

aside from that , is it possible to group public & secret gists separately ?

**Comment by lostintangent** [comment]
Maybe we can hide the “Starred Gists” node if you haven’t started any gists. And we can collapse it just default as well. That way, in your case, you wouldn’t even see it, and if you did star a Gist, it would be collapsed by default. That seems like a really good improvement, without needing to persist the collapsed state. Thoughts?

Regarding grouping public vs. private: that’s something I plan to do soon 👍

**Comment by ctf0** [comment]
awesome 🏆

**Comment by lostintangent** [comment]
@ctf0 FYI, the change to hide the starred gist node is now live 👍 As a result, I repurposed this issue to specifically track the enhancement to persist the expanded/collapsed state of the tree.

**Comment by ctf0** [comment]
many many thanks for ur quick support ❤️

**Comment by ctf0** [comment]
btw thanx for the delete gist command 🥇 , i was just going to ask for it.
