### ISSUE TITLE
Support SSO with the Hub and Gist CLIs

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gistpad#68]
Currently, we support SSO with the Git CLI, which enables GistPad to authenticate automatically if the user has already signed in with GitHub and has a token with gist permissions. However, we should also add SSO support for the Hub and [Gist](https://github.com/defunkt/gist) CLIs as well. That way, we can minimize the getting started experience for new users, that may be using other Gist-related tools.

**Comment by lumaxis** [comment]
@lostintangent Do you have a more detailed explanation of how this should currently work? I believe I'm correctly signed in to GitHub via the git CLI but GistPad still prompts me to sign in.

**Comment by lostintangent** [comment]
This issue is tracking adding SSO with the hub and gist CLIs (which I haven’t done yet!). GistPad attempts to perform SSO with the Git CLI, if it has a cached GitHub.com token, that includes the Gist scope. Otherwise, you just need to provide a new token to login. 

Does that help?

**Comment by lostintangent** [comment]
@lumaxis FYI, I just shipped an update which included your PR. Thanks again!

**Comment by lumaxis** [comment]
Sure, anytime! Thanks for the quick ship 🚢

**Comment by ctf0** [comment]
am not sure if this is the correct place, but atm SSO doesn't work correctly and every-time the pc shutdown the token is gone and have to be re-entered.

**Comment by lostintangent** [comment]
Closing this as won't fix, since I'll be focusing on integrating with the new VS Code auth provider, instead of trying to provide SSO with CLIs.
