### ISSUE TITLE
Ability to Group Github Gists

### ISSUE THREAD

**Issue by hdansou** [vsls-contrib/gistpad#7]
Github Gist does not support folders. However, we can consider setting tags in the description of a Gist, which could be used to create a grouping in vscode.

An application like lepton appends `#thistag` to the description of the gist.

Suggestions:
Option 1: use [#tag1, #tag2] at the beginning of the description
Option 1: use #thistag1 appended at the end of the description of a gist

**Comment by RandomFractals** [comment]
I think it would be better for gists tagging UX if you provided a menu option for a gist in your tree view to add tags.

The solution outlined above will not work for starred gists.

**Comment by lostintangent** [comment]
Hey all! As an update, I just shipped support for grouping gists by "type". This should help clean up/organize your gists a lot, **without needing to do anything extra** (e.g. adding tags). I don't think this replaces the need/value for arbitrary tags, but I wanted to share the update in the meantime.

<img width="200px" src="https://user-images.githubusercontent.com/116461/75098775-3fe62680-556f-11ea-8253-3198b00837e1.png" />

**Comment by lostintangent** [comment]
Just shipped an update that allows you to append tags to the end of the description (`#tag-name`), which will group your gists by that tag when grouping is enabled (per the screenshot above). You can add as many tags to a gist as you like, and the gist will be listed within all of those groups. 

<img width="200px" src="https://user-images.githubusercontent.com/116461/75264671-9c7e5700-57a4-11ea-9bee-eb61cfb9d2f0.png" />

I'm going to close this issue as resolved, but please let me know if you have any feedback/issues at all 👍

**Comment by RandomFractals** [comment]
this looks good. however, I don't think it works for gists that other devs created that I'd rather not touch or update their description.

Is there a way to add a slight tweak to it where we can add tags to gists we star?

**Comment by majkinetor** [comment]
I just noticed this and it is awesome. 

Thanks a lot.
