### ISSUE TITLE
collapse gist comments by default

### ISSUE THREAD

**Issue by ctf0** [vsls-contrib/gistpad#71]
showing the comments on gist open could be distractive specially for a long list of comments.

if u want to keep it as dynamic as possible, we can use an option to show/hide them instead.

**Comment by lostintangent** [comment]
There’s actually already a setting for this: “ GistPad: Show Comment Thread”. By default, it’s set to “whenNotEmpty”, but you can set it to “never” as well, which should provide the behavior you want. Thoughts?

**Comment by ctf0** [comment]
awesome, thank you
