### ISSUE TITLE
Gist refresh command missing

### ISSUE THREAD

**Issue by cburkins** [vsls-contrib/gistpad#79]
Sorry to ask a silly question, but I'm missing these handy controls on the Gistpad view within Explorer.  Is this a setting within VS Code ?   

![image](https://user-images.githubusercontent.com/9342308/71622927-20520380-2ba7-11ea-9496-ac9522749b8d.png)

**Comment by cburkins** [comment]
Here's what my view looks like in VS Code Explorer

![image](https://user-images.githubusercontent.com/9342308/71622987-72932480-2ba7-11ea-80fc-7db8f42247d8.png)

**Comment by cburkins** [comment]
And here's what my gistpad tab looks like

![image](https://user-images.githubusercontent.com/9342308/71623015-95bdd400-2ba7-11ea-8337-421ea977c5cf.png)

**Comment by cburkins** [comment]
It's a small thing, but it appears the only way to request gistpad to refresh from Github is via those small controls.   It appears there's not a separate command for that.

**Comment by lostintangent** [comment]
Thanks for reporting this! It seems like the action icons were regressed by #66, so I'm preparing an update that reverts that change.

**Comment by cburkins** [comment]
Whew !  I feel less silly now :) .   Thanks for the quick response, looking forward to the update, looks like a great tool !

**Comment by lostintangent** [comment]
This has been resolved! Update the GistPad extension to the latest version and you should see the icons again 👍 Let me know if you have any other feedback. Thanks!

**Comment by cburkins** [comment]
Just reloaded Gistpad, and it looks great now !  The controls are there.   Thanks for the incredibly quick response, and Happy New Year, @lostintangent

**Comment by lostintangent** [comment]
Thanks, you too! Please let me know about any feedback you may have. I _really_ want to make sure GistPad is awesome, so I need all the feedback I can get 👍

**Comment by ngouy** [comment]
@lostintangent do you mind if I try to send a PR to add it in command ? Something like
`> GistPad: reload` or `> GistPad: refresh`

![image](https://user-images.githubusercontent.com/12391171/71683351-55558600-2d60-11ea-975c-eb53c57ae269.png)

**Comment by lostintangent** [comment]
Sure! This command already exists, and so you’d simply need to change the “when” clause here, to “gistpad:state == SignedIn”: https://github.com/vsls-contrib/gistpad/blob/master/package.json#L575.
