### ISSUE TITLE
Add support for Block-based playgrounds

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/gistpad#89]
try this simple html/js vega-lite bar chart gist: 

https://gist.github.com/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9

Expected:

to see a rendered vega-lite bar chart web page preview similar to:

https://blockbuilder.org/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9

with bar.vl.png image preview and bar.vl.json editor open.

Actual result: only index.html is open by gist pad with a blank web page preview.

![gist-pad-vega-lite](https://user-images.githubusercontent.com/656833/71726467-d19da700-2dfc-11ea-8b7f-1cff885be58e.png)

**Comment by RandomFractals** [comment]
btw, a block gist with just html and inline js does work.

try: https://gist.github.com/cjbassin/4b34001dcda4d20ce57b410a89096681

![gistpad-html-block](https://user-images.githubusercontent.com/656833/71767329-efd4d700-2ed0-11ea-9139-563a7637204d.png)

**Comment by RandomFractals** [comment]
related: image view is broken.

should this displaly an image?

![gistpad-image-preview](https://user-images.githubusercontent.com/656833/71767365-2ca0ce00-2ed1-11ea-9c7f-0f4c82084adf.png)

**Comment by RandomFractals** [comment]
the good news is if you have Vega Viewer installed, it just works loading those custom .json graph files.

I am not sure how, but I am guessing it's b/c I have https vega specs loading in that ext. 

so, I guess we can claim https://github.com/RandomFractals/vscode-vega-viewer as GistPad compatible :)  w00t!

![gistpad-vega-viewer](https://user-images.githubusercontent.com/656833/71767419-d8e2b480-2ed1-11ea-96ad-f78235c2c6e0.png)

**Comment by lostintangent** [comment]
I’d expect a single HTML file to work, but there’s a bit more work to support the broader class of Blocks out there.

**Comment by RandomFractals** [comment]
true. I think it's close enough for now.

**Comment by lostintangent** [comment]
I just shipped an update that includes a bunch of improvements to make many (but not all!) Blocks work in GistPad. I'll keep churning through the issues, but things are much better now. Also, when you open a gist, you can paste a `bl.ocks.org` URL directly as opposed to needing to extract the `username/id` or `id`.

**Comment by RandomFractals** [comment]
@lostintangent that is awesome! Will play with it tomorrow.

Thanks for going the extra mile on this!

**Comment by RandomFractals** [comment]
btw, that last blocks update did take care of js loading and Vega blocks do load now ... thanks!

![vega-blocks-gistpad](https://user-images.githubusercontent.com/656833/71859117-629da800-30b3-11ea-9c54-7c2d2730e244.png)

**Comment by RandomFractals** [comment]
looks like simple d3.js with csv data loading blocks work too. nicely done! 

You can close this ticket if you'd like.

![gistpad-d3-block](https://user-images.githubusercontent.com/656833/71859436-74337f80-30b4-11ea-8563-a022f8a7c8ac.png)

**Comment by lostintangent** [comment]
Closing this since the bulk of Blocks support is shipped, and we can track any bugs in more specific issues. Thanks!

**Comment by RandomFractals** [comment]
@lostintangent good call! & much thanks for adding this for us data viz geeks.
