### ISSUE TITLE
"org.freedesktop.secrets was not provided by any .service files" when doing GistFS: New Gist for the first time

### ISSUE THREAD

**Issue by lichiku** [vsls-contrib/gistpad#9]
After successfully installed GistFS from the market place, when the "GistFS: New Gist" command was run for the first time, VSCode prompted me with the following error message:
`org.freedesktop.secrets was not provided by any .service files`

After some googling, install the following package on my system solved it:
_gnome-keyring_

Perhaps it would help to include some pointer in the Getting Started section of the document / webpage that gnome-keyring is a dependency?

**Comment by lostintangent** [comment]
Ah yeah this is good feedback. I’m using “keytar” to securely read and write the GH token, and I suppose that requires Gnome key ring to be installed on Linux. Thanks for reporting this!

**Comment by lostintangent** [comment]
@lichiku I just updated the readme to call out the need for `gnome-keyring` and `libsecret`.

**Comment by lichiku** [comment]
@lostintangent  Thank you for the ultra-fast response. The readme looks great and helpful now. I really like the idea and hope to see this great extension growing and shining. Thank you for your great job!
