### ISSUE TITLE
Open gists with only github username and gist id

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/gistpad#90]
we all know gists url base is https://gist.github.com

would be nice if gistpad could open gists with only github user name and gist id provided.

for example: cjbassin/4b34001dcda4d20ce57b410a89096681

mainly b/c most online dev tools that work with gists will have github username and gist id in their gist preview url & it's a pain to add gist base url when clipping them into gistpad.

try blocks for example: https://blockbuilder.org/search

or vega editor that shows gists with target file name too :) https://vega.github.io/editor/#/gist/455e1c7872c4b38a58b90df0c3d7b1b9/bar.vl.json

**Comment by lostintangent** [comment]
If you run the “GistPad: Open Gist Files” command, you can already specify just the ID (in addition to the full URL). So you specifically want to be able to use username _and_ ID?

**Comment by RandomFractals** [comment]
I think it should do both. Also, I was not aware of Open Gist Files. 

I tried it from Gists -> Open Gist... explorer link, which uses GistPad: Open Gist as Workspace command by default I believe.

Can you assign some keyboard shortcuts to both of those commands too?

Thanks!

**Comment by RandomFractals** [comment]
1 more, somewhat related:

That gist url quick input box goes away when vscode looses focus.

which is annoying when you open to enter gist and switch to browser to copy gist id :)

**Comment by lostintangent** [comment]
Sounds good. I’ll make these changes later today 👍

**Comment by lostintangent** [comment]
The following fixes have been pushed to master, and I'll ship an update with them this afternoon. Thanks again for the feedback!

1. Opening a gist via `username/id` format (in addition to by URL or by ID)
2. Added a keyboard shortcut for opening a gist: `ctrl+shift+o`/`cmd+shift+o`
3. Prevent the open gist quick pick from closing until you explicitly hit `<ESC>`
