### ISSUE TITLE
Add abilitiy to create secret playgrounds

### ISSUE THREAD

**Issue by negue** [vsls-contrib/gistpad#92]
It would be nice to be able to create secret playgrounds or an option for that :grin:

**Comment by lostintangent** [comment]
Thanks for reporting this! I had this on my backlog, but hadn't filed it yet 👍 Out of curiosity: would you likely want to create all of your playgrounds as secret? Or would you want a way to create public/secret as needed?

**Comment by negue** [comment]
it's probably depends on the playground to reproduce, 

I think if there was just another context item to create a secret one would be enough (for now an extra option wouldn't be needed, it was just an idea while writing up this "issue" ^^ )

**Comment by lostintangent** [comment]
Sounds good! I just pushed this change to master and will ship an update with it later this afternoon 👍

**Comment by negue** [comment]
Awesome! 🙌

**Comment by lostintangent** [comment]
This has been shipped in the latest update!
