### ISSUE TITLE
ctrl+shift+o keybinding of gistpad.openGist overrides native workbench.action.gotoSymbol

### ISSUE THREAD

**Issue by myfonj** [vsls-contrib/gistpad#93]
![image](https://user-images.githubusercontent.com/1761395/71889182-e2725380-3141-11ea-9ae8-70a168fed315.png)

https://github.com/vsls-contrib/gistpad/blob/4cf5538de143a9e40ca7b0ab28254ebc71504506/package.json#L488

Not that it is difficult to resolve it manually, but maybe some other default that does not clash with VSC default keybindings would be better. (<del><kbd>Ctrl</kbd>+<kbd>G</kbd> <kbd>Ctrl</kbd>+<kbd>O</kbd> perhaps?</del><ins>oh, nope, this would shadow `Go To Line`. Defaults are really hard.</ins>)

**Comment by zhanghnet9** [comment]
I removed all gistpad shortcuts to make vscode work normally.

**Comment by lostintangent** [comment]
I removed the default keybindings, since there aren’t any great options. I’ll simply allow users to create their own keybindings and will wait for more feedback before defining explicit keybindings.
