### ISSUE TITLE
List required personal access token scopes in setup instructions

### ISSUE THREAD

**Issue by Phrohdoh** [vsls-contrib/gistpad#94]
This may be "obvious" to those that are familiar with GitHub's OAuth scopes but may not be to others so it is my belief that explicitly listing these will improve the on-boarding process and get the user productive with GistPad even quicker.

https://github.com/vsls-contrib/gistpad/blob/e03371eec5661d0e15e54d88e962386ccde6e6c4/src/store/auth.ts#L53

**Comment by lostintangent** [comment]
Thanks for reaching out! I actually call out the need of the `gist` scope in step #2 of the [getting started](https://github.com/vsls-contrib/gistpad#getting-started) docs, but maybe that isn't prominent enough? I'd definitely love feedback on how to improve the onboarding experience!

**Comment by Phrohdoh** [comment]
Ah I see it is in the **Git+HTTPS Users** quote block.

Since I auth via ssh, instead of https, I skipped over this block multiple times.

Apologies!

**Comment by lostintangent** [comment]
Closing this as resolved, since I updated the docs to be more explicit. Thanks for the feedback!
